### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#275]
I am seeing this error in the console:

```
 TypeError: Cannot read property 'length' of undefined
    at wj.d (build.js:513)
    at fb.functionCall (build.js:203)
    at Object.<anonymous> (build.js:113)
    at k.$get.k.$digest (build.js:128)
    at k.$get.k.$apply (build.js:131)
    at m (build.js:86)
    at N (build.js:91)
    at XMLHttpRequest.w.onload (build.js:92)
````

The error occurs in Angular.

I cannot debug this now because the debug mode is broken, but this is a problem we need to address, sooner rather than later.

**Comment by pgiraud** [comment]
Not sure but this may be related to the fact that in https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/catalog/catalogdirective.js#L60
`items` should be changed to `themes`

If so, should be fixed with https://github.com/Geoportail-Luxembourg/geoportailv3/pull/276

**Comment by elemoine** [comment]
I just tested with my `elemoine_themes` branch (the one attached to #276) and the js error still occurred. So it looks like the problem is elsewhere.

**Comment by rmichaelis** [comment]
solved by merging #278

**Comment by pgiraud** [comment]
Closing.
